name: Github Actions

on:
  pull_request:
    branches:
      - main
  push:
    branches: 
      - main

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build file
        run: python3 setup.py sdist


  test:
    name: Running Units Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with pytest
        run: pytest
  
  packer_build:
    name: Packer Build
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      S3_KEY: ${{ secrets.S3_KEY }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      S3_URL_PREFIX: ${{ secrets.S3_URL_PREFIX }}
      AWS_KEY: ${{ secrets.AWS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      RDS_USERNAME: ${{ secrets.RDS_USERNAME }}
      RDS_PWD: ${{ secrets.RDS_PWD }}
      RDS_DB: ${{ secrets.RDS_DB }}
      RDS_HOST: ${{ secrets.RDS_HOST }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Build file
        run: python3 setup.py sdist
      - name: copy build file
        uses: canastro/copy-file-action@main
        with:
          source: "dist/webservice-0.0.1.tar.gz"
          target: "packer/webservice-0.0.1.tar.gz"
      - name: copy requirements file
        uses: canastro/copy-file-action@main
        with:
          source: "requirements.txt"
          target: "packer/requirements.txt"
      - name: Packer build
        uses: ExitoLab/packer_build_action_aws@v0.2.10
        with:
          templateFile: 'ec2-custom-ami.json'
          workingDir: 'packer'